config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  get 'pages/home'
  resources :questions do
    # post 'comments', to: 'comments#create'
    resources :comments, only: [:create, :destroy]
  end

  resources :comments do
    resources :comments
  end

  devise_for :users

  devise_scope :user do
    root 'devise/sessions#new'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :comments, as: :commentable, dependent: :destroy

    validates :title, presence: true, allow_blank: false
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  layout 'dashboard'
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @comment = Comment.new
    @comments = @question.comments.order("created_at DESC")
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to questions_path, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.haml
.card
  = form_for @question, html: {class: "form-horizontal"} do |f|
    - if @question.errors.any?
      #error_explanation
        - @question.errors.full_messages.each do |message|
          .alert.alert-danger{:role => "alert"}
            = message

    .card-header
      %strong Details of your question!!
    .card-body.card-block
      .row.form-group
        .col.col-md-3
          = f.label :title, class: "form-control-label"
        .col-12.col-md-9
          = f.text_field :title, class: "form-control", placeholder: "Enter your question ..."
    .card-footer
      = f.submit 'Save', class: "btn btn-primary btn-sm"
      = link_to "Back", questions_path, class: "btn btn-sm btn-dark"

app/views/questions/edit.html.haml
%h1 Editing question

= render 'form'

app/views/questions/index.html.haml
%h1 Listing questions

%table.table.table-striped
  %thead
    %tr
      %th Title
      %th Comments
      %th
      %th

  %tbody
    - @questions.includes(:comments).each do |question|
      %tr
        %td= question.title
        %td= link_to pluralize(question.comments.count, 'Comment'), question
        %td= link_to 'Edit', edit_question_path(question)
        %td= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Question', new_question_path, class: "btn btn-primary"

app/views/questions/new.html.haml
%h1 New question

= render 'form'

app/views/questions/show.html.haml
:javascript
  $(document).ready(function(){
    $(".sub-comment-form").hide();
    $(".comment-icon").on("click", function() {
      var comment_id = $(this).data("comment-id");
      $(".sub-comment-form-"+comment_id).toggle(800);
    });
  });

%hr/
/ Comments Form
%h1= @question.title
.card.my-4
  %h5.card-header Leave a Comment:
  .card-body
    = form_with model: [@question, Comment.new], local: true do |f|
      .form-group
        = f.text_area :body, class: "form-control", rows: "3"
      = f.submit "Comment", class: "btn btn-primary"
      = link_to "Back", questions_path, class: "btn btn-dark"
/ Single Comment

%h1= pluralize(@comments.count, 'Comment')
= render(partial: 'comments/comment', collection: @question.comments)