config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  get 'pages/home'
  resources :questions do
    # post 'comments', to: 'comments#create'
    resources :comments, only: [:create, :destroy]
  end

  resources :comments do
    resources :comments
  end

  devise_for :users

  devise_scope :user do
    root 'devise/sessions#new'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user

  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy

  validates :body, presence: true, allow_blank: false
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_commentable

  def new
    @comment = Comment.new
  end
  
  def create
    @comment = @commentable.comments.new comment_params
    @comment.user = current_user
    @comment.save
    redirect_back(fallback_location: root_path)
  end
  
  def destroy
    @comment = @commentable.comments.find(params[:id])
    @comment.destroy
    redirect_back(fallback_location: request.referer)
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :question_id)
  end

  def find_commentable
    @commentable = Comment.find(params[:comment_id]) if params[:comment_id]
    @commentable = Question.find(params[:question_id]) if params[:question_id]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
%hr/
.media.mb-4
  %img.d-flex.mr-3.rounded-circle{:alt => "", :src => "http://placehold.it/50x50"}/
  .media-body
    %h5.mt-0
      = comment.user.name
      - if current_user && current_user == comment.user
        = link_to question_comment_path(@question, comment), method: :delete, data: { confirm: 'Are you sure?', "toggle": "tooltip" }, title: "Delete Comment" do
          = fa_icon "trash", class: "text-muted pull-right", style: "color: red !important;"
    %h6.mt-0
      = comment.created_at.strftime("%d %b, %Y %I:%M:%S %p") 
    = comment.body
    = link_to "javascript:void(0)", class: "comment-icon", data: {"comment_id": comment.id, "toggle": "tooltip" }, title: "Add Comment" do
      = fa_icon "comment", class: "text-muted pull-right"
    .card.my-4.sub-comment-form{:class => "sub-comment-form-#{comment.id}"}
      %h5.card-header Leave a Comment:
      .card-body
        = form_with model: [comment, Comment.new], local: true do |f|
          .form-group
            = f.text_area :body, class: "form-control", rows: "3"
          = f.submit "Comment", class: "btn btn-primary"
          = link_to "Back", questions_path, class: "btn btn-dark"
    = render partial: 'comments/comment', collection: comment.comments
  

app/views/comments/create.html.haml
%h1 Comments#create
%p Find me in app/views/comments/create.html.haml